name: Continuous integration

concurrency:
  group: ${{ github.head_ref }}${{ github.ref }}-wallet-sdk
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Enable Corepack
        run: corepack enable

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install
        run: yarn

      - name: Eslint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Run coverage test
        run: yarn coverage

      - name: Yarn audit
        run: yarn npm audit --environment production --severity moderate

      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: coverallsapp/github-action@v2
        with:
          file: "coverage/lcov.info"

      - name: Coverage Comment
        uses: MishaKav/jest-coverage-comment@v1.0.23
        with:
          coverage-summary-path: coverage/coverage-summary.json

      - name: Publish lcov report
        uses: actions/upload-artifact@v4
        with:
          name: lcov-report.zip
          path: coverage/lcov-report
          if-no-files-found: error
